FROM golang:1.22.1-alpine

WORKDIR /api-gateway

COPY . .

RUN go get -u github.com/air-verse/air
RUN go install github.com/air-verse/air@latest

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/api-gateway

EXPOSE 443

CMD [ "./main" ]