// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.3
// source: proto/lesson_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//Types
type TopicPlan struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title     string    `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	UserId    uint32    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Objective string    `protobuf:"bytes,4,opt,name=objective,proto3" json:"objective,omitempty"`
	Standard  string    `protobuf:"bytes,5,opt,name=standard,proto3" json:"standard,omitempty"`
	Lesson    []*Lesson `protobuf:"bytes,6,rep,name=lesson,proto3" json:"lesson,omitempty"`
	Completed bool      `protobuf:"varint,7,opt,name=completed,proto3" json:"completed,omitempty"`
}

func (x *TopicPlan) Reset() {
	*x = TopicPlan{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lesson_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopicPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicPlan) ProtoMessage() {}

func (x *TopicPlan) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicPlan.ProtoReflect.Descriptor instead.
func (*TopicPlan) Descriptor() ([]byte, []int) {
	return file_proto_lesson_service_proto_rawDescGZIP(), []int{0}
}

func (x *TopicPlan) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TopicPlan) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TopicPlan) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TopicPlan) GetObjective() string {
	if x != nil {
		return x.Objective
	}
	return ""
}

func (x *TopicPlan) GetStandard() string {
	if x != nil {
		return x.Standard
	}
	return ""
}

func (x *TopicPlan) GetLesson() []*Lesson {
	if x != nil {
		return x.Lesson
	}
	return nil
}

func (x *TopicPlan) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

type Lesson struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string  `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	TopicPlanId uint32  `protobuf:"varint,3,opt,name=topic_plan_id,json=topicPlanId,proto3" json:"topic_plan_id,omitempty"`
	Objective   string  `protobuf:"bytes,4,opt,name=objective,proto3" json:"objective,omitempty"`
	Information string  `protobuf:"bytes,5,opt,name=information,proto3" json:"information,omitempty"`
	Tests       []*Test `protobuf:"bytes,6,rep,name=tests,proto3" json:"tests,omitempty"`
	Completed   bool    `protobuf:"varint,7,opt,name=completed,proto3" json:"completed,omitempty"`
}

func (x *Lesson) Reset() {
	*x = Lesson{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lesson_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lesson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lesson) ProtoMessage() {}

func (x *Lesson) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lesson.ProtoReflect.Descriptor instead.
func (*Lesson) Descriptor() ([]byte, []int) {
	return file_proto_lesson_service_proto_rawDescGZIP(), []int{1}
}

func (x *Lesson) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Lesson) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Lesson) GetTopicPlanId() uint32 {
	if x != nil {
		return x.TopicPlanId
	}
	return 0
}

func (x *Lesson) GetObjective() string {
	if x != nil {
		return x.Objective
	}
	return ""
}

func (x *Lesson) GetInformation() string {
	if x != nil {
		return x.Information
	}
	return ""
}

func (x *Lesson) GetTests() []*Test {
	if x != nil {
		return x.Tests
	}
	return nil
}

func (x *Lesson) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

type QuestionType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MultipleChoice string `protobuf:"bytes,1,opt,name=multiple_choice,json=multipleChoice,proto3" json:"multiple_choice,omitempty"`
	FillInTheBlank string `protobuf:"bytes,2,opt,name=fill_in_the_blank,json=fillInTheBlank,proto3" json:"fill_in_the_blank,omitempty"`
	ShortAnswer    string `protobuf:"bytes,3,opt,name=short_answer,json=shortAnswer,proto3" json:"short_answer,omitempty"`
	MatchOptions   string `protobuf:"bytes,4,opt,name=match_options,json=matchOptions,proto3" json:"match_options,omitempty"`
}

func (x *QuestionType) Reset() {
	*x = QuestionType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lesson_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuestionType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionType) ProtoMessage() {}

func (x *QuestionType) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionType.ProtoReflect.Descriptor instead.
func (*QuestionType) Descriptor() ([]byte, []int) {
	return file_proto_lesson_service_proto_rawDescGZIP(), []int{2}
}

func (x *QuestionType) GetMultipleChoice() string {
	if x != nil {
		return x.MultipleChoice
	}
	return ""
}

func (x *QuestionType) GetFillInTheBlank() string {
	if x != nil {
		return x.FillInTheBlank
	}
	return ""
}

func (x *QuestionType) GetShortAnswer() string {
	if x != nil {
		return x.ShortAnswer
	}
	return ""
}

func (x *QuestionType) GetMatchOptions() string {
	if x != nil {
		return x.MatchOptions
	}
	return ""
}

type Question struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuestionText string        `protobuf:"bytes,1,opt,name=question_text,json=questionText,proto3" json:"question_text,omitempty"`
	Type         *QuestionType `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Option       []string      `protobuf:"bytes,3,rep,name=option,proto3" json:"option,omitempty"`
	Answer       string        `protobuf:"bytes,4,opt,name=answer,proto3" json:"answer,omitempty"`
	AnswerIndex  uint32        `protobuf:"varint,5,opt,name=answer_index,json=answerIndex,proto3" json:"answer_index,omitempty"`
	Matches      []string      `protobuf:"bytes,6,rep,name=matches,proto3" json:"matches,omitempty"`
}

func (x *Question) Reset() {
	*x = Question{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lesson_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_proto_lesson_service_proto_rawDescGZIP(), []int{3}
}

func (x *Question) GetQuestionText() string {
	if x != nil {
		return x.QuestionText
	}
	return ""
}

func (x *Question) GetType() *QuestionType {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Question) GetOption() []string {
	if x != nil {
		return x.Option
	}
	return nil
}

func (x *Question) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *Question) GetAnswerIndex() uint32 {
	if x != nil {
		return x.AnswerIndex
	}
	return 0
}

func (x *Question) GetMatches() []string {
	if x != nil {
		return x.Matches
	}
	return nil
}

type Test struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            uint32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string      `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	QuestionCount uint32      `protobuf:"varint,3,opt,name=question_count,json=questionCount,proto3" json:"question_count,omitempty"`
	Questions     []*Question `protobuf:"bytes,4,rep,name=questions,proto3" json:"questions,omitempty"`
	LessonId      uint32      `protobuf:"varint,5,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	Passed        bool        `protobuf:"varint,6,opt,name=passed,proto3" json:"passed,omitempty"`
}

func (x *Test) Reset() {
	*x = Test{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lesson_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Test) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Test) ProtoMessage() {}

func (x *Test) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Test.ProtoReflect.Descriptor instead.
func (*Test) Descriptor() ([]byte, []int) {
	return file_proto_lesson_service_proto_rawDescGZIP(), []int{4}
}

func (x *Test) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Test) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Test) GetQuestionCount() uint32 {
	if x != nil {
		return x.QuestionCount
	}
	return 0
}

func (x *Test) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *Test) GetLessonId() uint32 {
	if x != nil {
		return x.LessonId
	}
	return 0
}

func (x *Test) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

//Requests
type GenerateQuickResponseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prompt string `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
}

func (x *GenerateQuickResponseRequest) Reset() {
	*x = GenerateQuickResponseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lesson_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateQuickResponseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateQuickResponseRequest) ProtoMessage() {}

func (x *GenerateQuickResponseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateQuickResponseRequest.ProtoReflect.Descriptor instead.
func (*GenerateQuickResponseRequest) Descriptor() ([]byte, []int) {
	return file_proto_lesson_service_proto_rawDescGZIP(), []int{5}
}

func (x *GenerateQuickResponseRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type GenerateTopicPlanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId          uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Prompt          string `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	NumberOfLessons uint32 `protobuf:"varint,3,opt,name=number_of_lessons,json=numberOfLessons,proto3" json:"number_of_lessons,omitempty"`
}

func (x *GenerateTopicPlanRequest) Reset() {
	*x = GenerateTopicPlanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lesson_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateTopicPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTopicPlanRequest) ProtoMessage() {}

func (x *GenerateTopicPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTopicPlanRequest.ProtoReflect.Descriptor instead.
func (*GenerateTopicPlanRequest) Descriptor() ([]byte, []int) {
	return file_proto_lesson_service_proto_rawDescGZIP(), []int{6}
}

func (x *GenerateTopicPlanRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GenerateTopicPlanRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GenerateTopicPlanRequest) GetNumberOfLessons() uint32 {
	if x != nil {
		return x.NumberOfLessons
	}
	return 0
}

type GenerateLessonsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TopicPlanId uint32 `protobuf:"varint,1,opt,name=topic_plan_id,json=topicPlanId,proto3" json:"topic_plan_id,omitempty"`
}

func (x *GenerateLessonsRequest) Reset() {
	*x = GenerateLessonsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lesson_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateLessonsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateLessonsRequest) ProtoMessage() {}

func (x *GenerateLessonsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateLessonsRequest.ProtoReflect.Descriptor instead.
func (*GenerateLessonsRequest) Descriptor() ([]byte, []int) {
	return file_proto_lesson_service_proto_rawDescGZIP(), []int{7}
}

func (x *GenerateLessonsRequest) GetTopicPlanId() uint32 {
	if x != nil {
		return x.TopicPlanId
	}
	return 0
}

type GenerateTestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LessonId          uint32 `protobuf:"varint,1,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	NumMultipleChoice uint32 `protobuf:"varint,2,opt,name=num_multiple_choice,json=numMultipleChoice,proto3" json:"num_multiple_choice,omitempty"`
	NumFillInTheBlank uint32 `protobuf:"varint,3,opt,name=num_fill_in_the_blank,json=numFillInTheBlank,proto3" json:"num_fill_in_the_blank,omitempty"`
	NumShortAnswer    uint32 `protobuf:"varint,4,opt,name=num_short_answer,json=numShortAnswer,proto3" json:"num_short_answer,omitempty"`
	NumMatchOptions   uint32 `protobuf:"varint,5,opt,name=num_match_options,json=numMatchOptions,proto3" json:"num_match_options,omitempty"`
}

func (x *GenerateTestRequest) Reset() {
	*x = GenerateTestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lesson_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTestRequest) ProtoMessage() {}

func (x *GenerateTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTestRequest.ProtoReflect.Descriptor instead.
func (*GenerateTestRequest) Descriptor() ([]byte, []int) {
	return file_proto_lesson_service_proto_rawDescGZIP(), []int{8}
}

func (x *GenerateTestRequest) GetLessonId() uint32 {
	if x != nil {
		return x.LessonId
	}
	return 0
}

func (x *GenerateTestRequest) GetNumMultipleChoice() uint32 {
	if x != nil {
		return x.NumMultipleChoice
	}
	return 0
}

func (x *GenerateTestRequest) GetNumFillInTheBlank() uint32 {
	if x != nil {
		return x.NumFillInTheBlank
	}
	return 0
}

func (x *GenerateTestRequest) GetNumShortAnswer() uint32 {
	if x != nil {
		return x.NumShortAnswer
	}
	return 0
}

func (x *GenerateTestRequest) GetNumMatchOptions() uint32 {
	if x != nil {
		return x.NumMatchOptions
	}
	return 0
}

type GetAllTopicPlansByUIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetAllTopicPlansByUIDRequest) Reset() {
	*x = GetAllTopicPlansByUIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lesson_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllTopicPlansByUIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTopicPlansByUIDRequest) ProtoMessage() {}

func (x *GetAllTopicPlansByUIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTopicPlansByUIDRequest.ProtoReflect.Descriptor instead.
func (*GetAllTopicPlansByUIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_lesson_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetAllTopicPlansByUIDRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetTopicPlanByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TopicPlanId uint32 `protobuf:"varint,1,opt,name=topic_plan_id,json=topicPlanId,proto3" json:"topic_plan_id,omitempty"`
}

func (x *GetTopicPlanByIDRequest) Reset() {
	*x = GetTopicPlanByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lesson_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTopicPlanByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopicPlanByIDRequest) ProtoMessage() {}

func (x *GetTopicPlanByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopicPlanByIDRequest.ProtoReflect.Descriptor instead.
func (*GetTopicPlanByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_lesson_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetTopicPlanByIDRequest) GetTopicPlanId() uint32 {
	if x != nil {
		return x.TopicPlanId
	}
	return 0
}

type GetLessonByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LessonId uint32 `protobuf:"varint,1,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
}

func (x *GetLessonByIDRequest) Reset() {
	*x = GetLessonByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lesson_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLessonByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLessonByIDRequest) ProtoMessage() {}

func (x *GetLessonByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLessonByIDRequest.ProtoReflect.Descriptor instead.
func (*GetLessonByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_lesson_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetLessonByIDRequest) GetLessonId() uint32 {
	if x != nil {
		return x.LessonId
	}
	return 0
}

type GetAllLessonPlansByTopicIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TopicPlanId uint32 `protobuf:"varint,1,opt,name=topic_plan_id,json=topicPlanId,proto3" json:"topic_plan_id,omitempty"`
}

func (x *GetAllLessonPlansByTopicIDRequest) Reset() {
	*x = GetAllLessonPlansByTopicIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lesson_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllLessonPlansByTopicIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllLessonPlansByTopicIDRequest) ProtoMessage() {}

func (x *GetAllLessonPlansByTopicIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllLessonPlansByTopicIDRequest.ProtoReflect.Descriptor instead.
func (*GetAllLessonPlansByTopicIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_lesson_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetAllLessonPlansByTopicIDRequest) GetTopicPlanId() uint32 {
	if x != nil {
		return x.TopicPlanId
	}
	return 0
}

type GetAllTestsByLessonIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LessonId uint32 `protobuf:"varint,1,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
}

func (x *GetAllTestsByLessonIDRequest) Reset() {
	*x = GetAllTestsByLessonIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lesson_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllTestsByLessonIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTestsByLessonIDRequest) ProtoMessage() {}

func (x *GetAllTestsByLessonIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTestsByLessonIDRequest.ProtoReflect.Descriptor instead.
func (*GetAllTestsByLessonIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_lesson_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetAllTestsByLessonIDRequest) GetLessonId() uint32 {
	if x != nil {
		return x.LessonId
	}
	return 0
}

type GetAllQuestionsByTestIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TestId uint32 `protobuf:"varint,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
}

func (x *GetAllQuestionsByTestIDRequest) Reset() {
	*x = GetAllQuestionsByTestIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lesson_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllQuestionsByTestIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllQuestionsByTestIDRequest) ProtoMessage() {}

func (x *GetAllQuestionsByTestIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllQuestionsByTestIDRequest.ProtoReflect.Descriptor instead.
func (*GetAllQuestionsByTestIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_lesson_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetAllQuestionsByTestIDRequest) GetTestId() uint32 {
	if x != nil {
		return x.TestId
	}
	return 0
}

type GradeTestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TestId      uint32   `protobuf:"varint,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	Answers     []string `protobuf:"bytes,2,rep,name=answers,proto3" json:"answers,omitempty"`
	LessonId    uint32   `protobuf:"varint,3,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	TopicPlanId uint32   `protobuf:"varint,4,opt,name=topic_plan_id,json=topicPlanId,proto3" json:"topic_plan_id,omitempty"`
}

func (x *GradeTestRequest) Reset() {
	*x = GradeTestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lesson_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GradeTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeTestRequest) ProtoMessage() {}

func (x *GradeTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeTestRequest.ProtoReflect.Descriptor instead.
func (*GradeTestRequest) Descriptor() ([]byte, []int) {
	return file_proto_lesson_service_proto_rawDescGZIP(), []int{15}
}

func (x *GradeTestRequest) GetTestId() uint32 {
	if x != nil {
		return x.TestId
	}
	return 0
}

func (x *GradeTestRequest) GetAnswers() []string {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *GradeTestRequest) GetLessonId() uint32 {
	if x != nil {
		return x.LessonId
	}
	return 0
}

func (x *GradeTestRequest) GetTopicPlanId() uint32 {
	if x != nil {
		return x.TopicPlanId
	}
	return 0
}

//Responses
type GenerateQuickResponseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *GenerateQuickResponseResponse) Reset() {
	*x = GenerateQuickResponseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lesson_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateQuickResponseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateQuickResponseResponse) ProtoMessage() {}

func (x *GenerateQuickResponseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateQuickResponseResponse.ProtoReflect.Descriptor instead.
func (*GenerateQuickResponseResponse) Descriptor() ([]byte, []int) {
	return file_proto_lesson_service_proto_rawDescGZIP(), []int{16}
}

func (x *GenerateQuickResponseResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type GenerateTopicPlanResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TopicPlan *TopicPlan `protobuf:"bytes,1,opt,name=topic_plan,json=topicPlan,proto3" json:"topic_plan,omitempty"`
}

func (x *GenerateTopicPlanResponse) Reset() {
	*x = GenerateTopicPlanResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lesson_service_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateTopicPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTopicPlanResponse) ProtoMessage() {}

func (x *GenerateTopicPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_service_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTopicPlanResponse.ProtoReflect.Descriptor instead.
func (*GenerateTopicPlanResponse) Descriptor() ([]byte, []int) {
	return file_proto_lesson_service_proto_rawDescGZIP(), []int{17}
}

func (x *GenerateTopicPlanResponse) GetTopicPlan() *TopicPlan {
	if x != nil {
		return x.TopicPlan
	}
	return nil
}

type GenerateLessonsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lessons []*Lesson `protobuf:"bytes,1,rep,name=lessons,proto3" json:"lessons,omitempty"`
}

func (x *GenerateLessonsResponse) Reset() {
	*x = GenerateLessonsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lesson_service_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateLessonsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateLessonsResponse) ProtoMessage() {}

func (x *GenerateLessonsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_service_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateLessonsResponse.ProtoReflect.Descriptor instead.
func (*GenerateLessonsResponse) Descriptor() ([]byte, []int) {
	return file_proto_lesson_service_proto_rawDescGZIP(), []int{18}
}

func (x *GenerateLessonsResponse) GetLessons() []*Lesson {
	if x != nil {
		return x.Lessons
	}
	return nil
}

type GenerateTestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Test *Test `protobuf:"bytes,1,opt,name=test,proto3" json:"test,omitempty"`
}

func (x *GenerateTestResponse) Reset() {
	*x = GenerateTestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lesson_service_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTestResponse) ProtoMessage() {}

func (x *GenerateTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_service_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTestResponse.ProtoReflect.Descriptor instead.
func (*GenerateTestResponse) Descriptor() ([]byte, []int) {
	return file_proto_lesson_service_proto_rawDescGZIP(), []int{19}
}

func (x *GenerateTestResponse) GetTest() *Test {
	if x != nil {
		return x.Test
	}
	return nil
}

type GetAllTopicPlansByUIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TopicPlans []*TopicPlan `protobuf:"bytes,1,rep,name=topic_plans,json=topicPlans,proto3" json:"topic_plans,omitempty"`
}

func (x *GetAllTopicPlansByUIDResponse) Reset() {
	*x = GetAllTopicPlansByUIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lesson_service_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllTopicPlansByUIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTopicPlansByUIDResponse) ProtoMessage() {}

func (x *GetAllTopicPlansByUIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_service_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTopicPlansByUIDResponse.ProtoReflect.Descriptor instead.
func (*GetAllTopicPlansByUIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_lesson_service_proto_rawDescGZIP(), []int{20}
}

func (x *GetAllTopicPlansByUIDResponse) GetTopicPlans() []*TopicPlan {
	if x != nil {
		return x.TopicPlans
	}
	return nil
}

type GetTopicPlanByIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TopicPlan *TopicPlan `protobuf:"bytes,1,opt,name=topic_plan,json=topicPlan,proto3" json:"topic_plan,omitempty"`
}

func (x *GetTopicPlanByIDResponse) Reset() {
	*x = GetTopicPlanByIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lesson_service_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTopicPlanByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopicPlanByIDResponse) ProtoMessage() {}

func (x *GetTopicPlanByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_service_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopicPlanByIDResponse.ProtoReflect.Descriptor instead.
func (*GetTopicPlanByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_lesson_service_proto_rawDescGZIP(), []int{21}
}

func (x *GetTopicPlanByIDResponse) GetTopicPlan() *TopicPlan {
	if x != nil {
		return x.TopicPlan
	}
	return nil
}

type GetLessonByIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lesson *Lesson `protobuf:"bytes,1,opt,name=lesson,proto3" json:"lesson,omitempty"`
}

func (x *GetLessonByIDResponse) Reset() {
	*x = GetLessonByIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lesson_service_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLessonByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLessonByIDResponse) ProtoMessage() {}

func (x *GetLessonByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_service_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLessonByIDResponse.ProtoReflect.Descriptor instead.
func (*GetLessonByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_lesson_service_proto_rawDescGZIP(), []int{22}
}

func (x *GetLessonByIDResponse) GetLesson() *Lesson {
	if x != nil {
		return x.Lesson
	}
	return nil
}

type GetAllLessonPlansByTopicIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lessons []*Lesson `protobuf:"bytes,1,rep,name=lessons,proto3" json:"lessons,omitempty"`
}

func (x *GetAllLessonPlansByTopicIDResponse) Reset() {
	*x = GetAllLessonPlansByTopicIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lesson_service_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllLessonPlansByTopicIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllLessonPlansByTopicIDResponse) ProtoMessage() {}

func (x *GetAllLessonPlansByTopicIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_service_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllLessonPlansByTopicIDResponse.ProtoReflect.Descriptor instead.
func (*GetAllLessonPlansByTopicIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_lesson_service_proto_rawDescGZIP(), []int{23}
}

func (x *GetAllLessonPlansByTopicIDResponse) GetLessons() []*Lesson {
	if x != nil {
		return x.Lessons
	}
	return nil
}

type GetAllTestsByLessonIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tests []*Test `protobuf:"bytes,1,rep,name=tests,proto3" json:"tests,omitempty"`
}

func (x *GetAllTestsByLessonIDResponse) Reset() {
	*x = GetAllTestsByLessonIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lesson_service_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllTestsByLessonIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTestsByLessonIDResponse) ProtoMessage() {}

func (x *GetAllTestsByLessonIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_service_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTestsByLessonIDResponse.ProtoReflect.Descriptor instead.
func (*GetAllTestsByLessonIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_lesson_service_proto_rawDescGZIP(), []int{24}
}

func (x *GetAllTestsByLessonIDResponse) GetTests() []*Test {
	if x != nil {
		return x.Tests
	}
	return nil
}

type GetAllQuestionsByTestIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Questions []*Question `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
}

func (x *GetAllQuestionsByTestIDResponse) Reset() {
	*x = GetAllQuestionsByTestIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lesson_service_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllQuestionsByTestIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllQuestionsByTestIDResponse) ProtoMessage() {}

func (x *GetAllQuestionsByTestIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_service_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllQuestionsByTestIDResponse.ProtoReflect.Descriptor instead.
func (*GetAllQuestionsByTestIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_lesson_service_proto_rawDescGZIP(), []int{25}
}

func (x *GetAllQuestionsByTestIDResponse) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

type GradeTestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Score    int32            `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	Feedback map[int32]string `protobuf:"bytes,2,rep,name=feedback,proto3" json:"feedback,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Passed   bool             `protobuf:"varint,3,opt,name=passed,proto3" json:"passed,omitempty"`
}

func (x *GradeTestResponse) Reset() {
	*x = GradeTestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lesson_service_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GradeTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeTestResponse) ProtoMessage() {}

func (x *GradeTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_service_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeTestResponse.ProtoReflect.Descriptor instead.
func (*GradeTestResponse) Descriptor() ([]byte, []int) {
	return file_proto_lesson_service_proto_rawDescGZIP(), []int{26}
}

func (x *GradeTestResponse) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *GradeTestResponse) GetFeedback() map[int32]string {
	if x != nil {
		return x.Feedback
	}
	return nil
}

func (x *GradeTestResponse) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

var File_proto_lesson_service_proto protoreflect.FileDescriptor

var file_proto_lesson_service_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xc9, 0x01, 0x0a, 0x09, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x50, 0x6c, 0x61,
	0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x12, 0x25, 0x0a, 0x06, 0x6c, 0x65,
	0x73, 0x73, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x52, 0x06, 0x6c, 0x65, 0x73, 0x73, 0x6f,
	0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x22,
	0xd3, 0x01, 0x0a, 0x06, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x22, 0x0a, 0x0d, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x50, 0x6c,
	0x61, 0x6e, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x05, 0x74, 0x65, 0x73, 0x74, 0x73, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x65, 0x73, 0x74,
	0x52, 0x05, 0x74, 0x65, 0x73, 0x74, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x65, 0x64, 0x22, 0xaa, 0x01, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69,
	0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70,
	0x6c, 0x65, 0x5f, 0x63, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x12,
	0x29, 0x0a, 0x11, 0x66, 0x69, 0x6c, 0x6c, 0x5f, 0x69, 0x6e, 0x5f, 0x74, 0x68, 0x65, 0x5f, 0x62,
	0x6c, 0x61, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x66, 0x69, 0x6c, 0x6c,
	0x49, 0x6e, 0x54, 0x68, 0x65, 0x42, 0x6c, 0x61, 0x6e, 0x6b, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x5f, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x23, 0x0a,
	0x0d, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x22, 0xc5, 0x01, 0x0a, 0x08, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x23, 0x0a, 0x0d, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x65, 0x78, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e,
	0x54, 0x65, 0x78, 0x74, 0x12, 0x27, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x73, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x21, 0x0a,
	0x0c, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0b, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x22, 0xb7, 0x01, 0x0a, 0x04, 0x54,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0d, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x2d, 0x0a, 0x09, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x73,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x1b, 0x0a, 0x09, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x70, 0x61, 0x73, 0x73, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x70, 0x61,
	0x73, 0x73, 0x65, 0x64, 0x22, 0x36, 0x0a, 0x1c, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x51, 0x75, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x22, 0x77, 0x0a, 0x18,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x50, 0x6c, 0x61,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x5f, 0x6f, 0x66, 0x5f, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x4c, 0x65,
	0x73, 0x73, 0x6f, 0x6e, 0x73, 0x22, 0x3c, 0x0a, 0x16, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x22, 0x0a, 0x0d, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x50, 0x6c, 0x61,
	0x6e, 0x49, 0x64, 0x22, 0xea, 0x01, 0x0a, 0x13, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6c,
	0x65, 0x73, 0x73, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08,
	0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x13, 0x6e, 0x75, 0x6d, 0x5f,
	0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x5f, 0x63, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x11, 0x6e, 0x75, 0x6d, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70,
	0x6c, 0x65, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x30, 0x0a, 0x15, 0x6e, 0x75, 0x6d, 0x5f,
	0x66, 0x69, 0x6c, 0x6c, 0x5f, 0x69, 0x6e, 0x5f, 0x74, 0x68, 0x65, 0x5f, 0x62, 0x6c, 0x61, 0x6e,
	0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x11, 0x6e, 0x75, 0x6d, 0x46, 0x69, 0x6c, 0x6c,
	0x49, 0x6e, 0x54, 0x68, 0x65, 0x42, 0x6c, 0x61, 0x6e, 0x6b, 0x12, 0x28, 0x0a, 0x10, 0x6e, 0x75,
	0x6d, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x6e, 0x75, 0x6d, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x41, 0x6e,
	0x73, 0x77, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x11, 0x6e, 0x75, 0x6d, 0x5f, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0f, 0x6e, 0x75, 0x6d, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x22, 0x37, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x50,
	0x6c, 0x61, 0x6e, 0x73, 0x42, 0x79, 0x55, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3d, 0x0a, 0x17, 0x47, 0x65, 0x74,
	0x54, 0x6f, 0x70, 0x69, 0x63, 0x50, 0x6c, 0x61, 0x6e, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0d, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x5f, 0x70, 0x6c,
	0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x74, 0x6f, 0x70,
	0x69, 0x63, 0x50, 0x6c, 0x61, 0x6e, 0x49, 0x64, 0x22, 0x33, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4c,
	0x65, 0x73, 0x73, 0x6f, 0x6e, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x08, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x47, 0x0a,
	0x21, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x50, 0x6c, 0x61,
	0x6e, 0x73, 0x42, 0x79, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x22, 0x0a, 0x0d, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x5f, 0x70, 0x6c, 0x61, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x74, 0x6f, 0x70, 0x69, 0x63,
	0x50, 0x6c, 0x61, 0x6e, 0x49, 0x64, 0x22, 0x3b, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x54, 0x65, 0x73, 0x74, 0x73, 0x42, 0x79, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x49, 0x44, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6c, 0x65, 0x73, 0x73, 0x6f,
	0x6e, 0x49, 0x64, 0x22, 0x39, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x51, 0x75, 0x65,
	0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x79, 0x54, 0x65, 0x73, 0x74, 0x49, 0x44, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x74, 0x65, 0x73, 0x74, 0x49, 0x64, 0x22, 0x86,
	0x01, 0x0a, 0x10, 0x47, 0x72, 0x61, 0x64, 0x65, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x74, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6c, 0x65, 0x73, 0x73, 0x6f,
	0x6e, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x5f, 0x70, 0x6c, 0x61,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x74, 0x6f, 0x70, 0x69,
	0x63, 0x50, 0x6c, 0x61, 0x6e, 0x49, 0x64, 0x22, 0x3b, 0x0a, 0x1d, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x51, 0x75, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4c, 0x0a, 0x19, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x54, 0x6f, 0x70, 0x69, 0x63, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2f, 0x0a, 0x0a, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x6f,
	0x70, 0x69, 0x63, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x09, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x50, 0x6c,
	0x61, 0x6e, 0x22, 0x42, 0x0a, 0x17, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4c, 0x65,
	0x73, 0x73, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a,
	0x07, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x52, 0x07, 0x6c,
	0x65, 0x73, 0x73, 0x6f, 0x6e, 0x73, 0x22, 0x37, 0x0a, 0x14, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f,
	0x0a, 0x04, 0x74, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x52, 0x04, 0x74, 0x65, 0x73, 0x74, 0x22,
	0x52, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x50, 0x6c,
	0x61, 0x6e, 0x73, 0x42, 0x79, 0x55, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x31, 0x0a, 0x0b, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x6f,
	0x70, 0x69, 0x63, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x0a, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x50, 0x6c,
	0x61, 0x6e, 0x73, 0x22, 0x4b, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x50,
	0x6c, 0x61, 0x6e, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2f, 0x0a, 0x0a, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x6f, 0x70, 0x69,
	0x63, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x09, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x50, 0x6c, 0x61, 0x6e,
	0x22, 0x3e, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x42, 0x79, 0x49,
	0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x6c, 0x65, 0x73,
	0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x52, 0x06, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e,
	0x22, 0x4d, 0x0a, 0x22, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e,
	0x50, 0x6c, 0x61, 0x6e, 0x73, 0x42, 0x79, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x49, 0x44, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x07, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x52, 0x07, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x73, 0x22,
	0x42, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x54, 0x65, 0x73, 0x74, 0x73, 0x42, 0x79,
	0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x21, 0x0a, 0x05, 0x74, 0x65, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x52, 0x05, 0x74, 0x65,
	0x73, 0x74, 0x73, 0x22, 0x50, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x51, 0x75, 0x65,
	0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x79, 0x54, 0x65, 0x73, 0x74, 0x49, 0x44, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x09, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xc2, 0x01, 0x0a, 0x11, 0x47, 0x72, 0x61, 0x64, 0x65, 0x54,
	0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x63, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72,
	0x65, 0x12, 0x42, 0x0a, 0x08, 0x66, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x72, 0x61, 0x64,
	0x65, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x46, 0x65,
	0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x66, 0x65, 0x65,
	0x64, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x73, 0x73, 0x65, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x70, 0x61, 0x73, 0x73, 0x65, 0x64, 0x1a, 0x3b, 0x0a,
	0x0d, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x32, 0xed, 0x07, 0x0a, 0x0d, 0x4c,
	0x65, 0x73, 0x73, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x62, 0x0a, 0x15,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x51, 0x75, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x51, 0x75, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x51, 0x75, 0x69, 0x63, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x56, 0x0a, 0x11, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x70, 0x69,
	0x63, 0x50, 0x6c, 0x61, 0x6e, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x50, 0x6c, 0x61, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x50, 0x6c, 0x61, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x0f, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x73, 0x12, 0x1d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x73, 0x73,
	0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x73, 0x73, 0x6f,
	0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x0d, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x54, 0x65, 0x73, 0x74, 0x73, 0x12, 0x1a, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x54, 0x65, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x62, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x54, 0x6f,
	0x70, 0x69, 0x63, 0x50, 0x6c, 0x61, 0x6e, 0x73, 0x42, 0x79, 0x55, 0x49, 0x44, 0x12, 0x23, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x54, 0x6f, 0x70, 0x69,
	0x63, 0x50, 0x6c, 0x61, 0x6e, 0x73, 0x42, 0x79, 0x55, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x50, 0x6c, 0x61, 0x6e, 0x73, 0x42, 0x79, 0x55, 0x49, 0x44,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4c,
	0x65, 0x73, 0x73, 0x6f, 0x6e, 0x42, 0x79, 0x49, 0x44, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x42, 0x79, 0x49, 0x44, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47,
	0x65, 0x74, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x71, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4c, 0x65,
	0x73, 0x73, 0x6f, 0x6e, 0x50, 0x6c, 0x61, 0x6e, 0x73, 0x42, 0x79, 0x54, 0x6f, 0x70, 0x69, 0x63,
	0x49, 0x44, 0x12, 0x28, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x50, 0x6c, 0x61, 0x6e, 0x73, 0x42, 0x79, 0x54, 0x6f,
	0x70, 0x69, 0x63, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4c, 0x65, 0x73, 0x73, 0x6f,
	0x6e, 0x50, 0x6c, 0x61, 0x6e, 0x73, 0x42, 0x79, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x49, 0x44, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x62, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x54, 0x65, 0x73, 0x74, 0x73, 0x42, 0x79, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x49, 0x44,
	0x12, 0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x54,
	0x65, 0x73, 0x74, 0x73, 0x42, 0x79, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x49, 0x44, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x54, 0x65, 0x73, 0x74, 0x73, 0x42, 0x79, 0x4c, 0x65, 0x73, 0x73, 0x6f,
	0x6e, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x68, 0x0a, 0x17, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x79,
	0x54, 0x65, 0x73, 0x74, 0x49, 0x44, 0x12, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x79,
	0x54, 0x65, 0x73, 0x74, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x51, 0x75, 0x65, 0x73,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x79, 0x54, 0x65, 0x73, 0x74, 0x49, 0x44, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x09, 0x47, 0x72, 0x61, 0x64, 0x65, 0x54, 0x65,
	0x73, 0x74, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x72, 0x61, 0x64, 0x65,
	0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x72, 0x61, 0x64, 0x65, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x69,
	0x63, 0x50, 0x6c, 0x61, 0x6e, 0x42, 0x79, 0x49, 0x44, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x50, 0x6c, 0x61, 0x6e, 0x42, 0x79,
	0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x50, 0x6c, 0x61, 0x6e, 0x42, 0x79,
	0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1a, 0x5a, 0x18, 0x6c, 0x65,
	0x73, 0x73, 0x6f, 0x6e, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_lesson_service_proto_rawDescOnce sync.Once
	file_proto_lesson_service_proto_rawDescData = file_proto_lesson_service_proto_rawDesc
)

func file_proto_lesson_service_proto_rawDescGZIP() []byte {
	file_proto_lesson_service_proto_rawDescOnce.Do(func() {
		file_proto_lesson_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_lesson_service_proto_rawDescData)
	})
	return file_proto_lesson_service_proto_rawDescData
}

var file_proto_lesson_service_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_proto_lesson_service_proto_goTypes = []interface{}{
	(*TopicPlan)(nil),                          // 0: proto.TopicPlan
	(*Lesson)(nil),                             // 1: proto.Lesson
	(*QuestionType)(nil),                       // 2: proto.QuestionType
	(*Question)(nil),                           // 3: proto.Question
	(*Test)(nil),                               // 4: proto.Test
	(*GenerateQuickResponseRequest)(nil),       // 5: proto.GenerateQuickResponseRequest
	(*GenerateTopicPlanRequest)(nil),           // 6: proto.GenerateTopicPlanRequest
	(*GenerateLessonsRequest)(nil),             // 7: proto.GenerateLessonsRequest
	(*GenerateTestRequest)(nil),                // 8: proto.GenerateTestRequest
	(*GetAllTopicPlansByUIDRequest)(nil),       // 9: proto.GetAllTopicPlansByUIDRequest
	(*GetTopicPlanByIDRequest)(nil),            // 10: proto.GetTopicPlanByIDRequest
	(*GetLessonByIDRequest)(nil),               // 11: proto.GetLessonByIDRequest
	(*GetAllLessonPlansByTopicIDRequest)(nil),  // 12: proto.GetAllLessonPlansByTopicIDRequest
	(*GetAllTestsByLessonIDRequest)(nil),       // 13: proto.GetAllTestsByLessonIDRequest
	(*GetAllQuestionsByTestIDRequest)(nil),     // 14: proto.GetAllQuestionsByTestIDRequest
	(*GradeTestRequest)(nil),                   // 15: proto.GradeTestRequest
	(*GenerateQuickResponseResponse)(nil),      // 16: proto.GenerateQuickResponseResponse
	(*GenerateTopicPlanResponse)(nil),          // 17: proto.GenerateTopicPlanResponse
	(*GenerateLessonsResponse)(nil),            // 18: proto.GenerateLessonsResponse
	(*GenerateTestResponse)(nil),               // 19: proto.GenerateTestResponse
	(*GetAllTopicPlansByUIDResponse)(nil),      // 20: proto.GetAllTopicPlansByUIDResponse
	(*GetTopicPlanByIDResponse)(nil),           // 21: proto.GetTopicPlanByIDResponse
	(*GetLessonByIDResponse)(nil),              // 22: proto.GetLessonByIDResponse
	(*GetAllLessonPlansByTopicIDResponse)(nil), // 23: proto.GetAllLessonPlansByTopicIDResponse
	(*GetAllTestsByLessonIDResponse)(nil),      // 24: proto.GetAllTestsByLessonIDResponse
	(*GetAllQuestionsByTestIDResponse)(nil),    // 25: proto.GetAllQuestionsByTestIDResponse
	(*GradeTestResponse)(nil),                  // 26: proto.GradeTestResponse
	nil,                                        // 27: proto.GradeTestResponse.FeedbackEntry
}
var file_proto_lesson_service_proto_depIdxs = []int32{
	1,  // 0: proto.TopicPlan.lesson:type_name -> proto.Lesson
	4,  // 1: proto.Lesson.tests:type_name -> proto.Test
	2,  // 2: proto.Question.type:type_name -> proto.QuestionType
	3,  // 3: proto.Test.questions:type_name -> proto.Question
	0,  // 4: proto.GenerateTopicPlanResponse.topic_plan:type_name -> proto.TopicPlan
	1,  // 5: proto.GenerateLessonsResponse.lessons:type_name -> proto.Lesson
	4,  // 6: proto.GenerateTestResponse.test:type_name -> proto.Test
	0,  // 7: proto.GetAllTopicPlansByUIDResponse.topic_plans:type_name -> proto.TopicPlan
	0,  // 8: proto.GetTopicPlanByIDResponse.topic_plan:type_name -> proto.TopicPlan
	1,  // 9: proto.GetLessonByIDResponse.lesson:type_name -> proto.Lesson
	1,  // 10: proto.GetAllLessonPlansByTopicIDResponse.lessons:type_name -> proto.Lesson
	4,  // 11: proto.GetAllTestsByLessonIDResponse.tests:type_name -> proto.Test
	3,  // 12: proto.GetAllQuestionsByTestIDResponse.questions:type_name -> proto.Question
	27, // 13: proto.GradeTestResponse.feedback:type_name -> proto.GradeTestResponse.FeedbackEntry
	5,  // 14: proto.LessonService.GenerateQuickResponse:input_type -> proto.GenerateQuickResponseRequest
	6,  // 15: proto.LessonService.GenerateTopicPlan:input_type -> proto.GenerateTopicPlanRequest
	7,  // 16: proto.LessonService.GenerateLessons:input_type -> proto.GenerateLessonsRequest
	8,  // 17: proto.LessonService.GenerateTests:input_type -> proto.GenerateTestRequest
	9,  // 18: proto.LessonService.GetAllTopicPlansByUID:input_type -> proto.GetAllTopicPlansByUIDRequest
	11, // 19: proto.LessonService.GetLessonByID:input_type -> proto.GetLessonByIDRequest
	12, // 20: proto.LessonService.GetAllLessonPlansByTopicID:input_type -> proto.GetAllLessonPlansByTopicIDRequest
	13, // 21: proto.LessonService.GetAllTestsByLessonID:input_type -> proto.GetAllTestsByLessonIDRequest
	14, // 22: proto.LessonService.GetAllQuestionsByTestID:input_type -> proto.GetAllQuestionsByTestIDRequest
	15, // 23: proto.LessonService.GradeTest:input_type -> proto.GradeTestRequest
	10, // 24: proto.LessonService.GetTopicPlanByID:input_type -> proto.GetTopicPlanByIDRequest
	16, // 25: proto.LessonService.GenerateQuickResponse:output_type -> proto.GenerateQuickResponseResponse
	17, // 26: proto.LessonService.GenerateTopicPlan:output_type -> proto.GenerateTopicPlanResponse
	18, // 27: proto.LessonService.GenerateLessons:output_type -> proto.GenerateLessonsResponse
	19, // 28: proto.LessonService.GenerateTests:output_type -> proto.GenerateTestResponse
	20, // 29: proto.LessonService.GetAllTopicPlansByUID:output_type -> proto.GetAllTopicPlansByUIDResponse
	22, // 30: proto.LessonService.GetLessonByID:output_type -> proto.GetLessonByIDResponse
	23, // 31: proto.LessonService.GetAllLessonPlansByTopicID:output_type -> proto.GetAllLessonPlansByTopicIDResponse
	24, // 32: proto.LessonService.GetAllTestsByLessonID:output_type -> proto.GetAllTestsByLessonIDResponse
	25, // 33: proto.LessonService.GetAllQuestionsByTestID:output_type -> proto.GetAllQuestionsByTestIDResponse
	26, // 34: proto.LessonService.GradeTest:output_type -> proto.GradeTestResponse
	21, // 35: proto.LessonService.GetTopicPlanByID:output_type -> proto.GetTopicPlanByIDResponse
	25, // [25:36] is the sub-list for method output_type
	14, // [14:25] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_lesson_service_proto_init() }
func file_proto_lesson_service_proto_init() {
	if File_proto_lesson_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_lesson_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopicPlan); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lesson_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Lesson); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lesson_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuestionType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lesson_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Question); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lesson_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Test); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lesson_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateQuickResponseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lesson_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateTopicPlanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lesson_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateLessonsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lesson_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateTestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lesson_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllTopicPlansByUIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lesson_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTopicPlanByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lesson_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLessonByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lesson_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllLessonPlansByTopicIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lesson_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllTestsByLessonIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lesson_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllQuestionsByTestIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lesson_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GradeTestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lesson_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateQuickResponseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lesson_service_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateTopicPlanResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lesson_service_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateLessonsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lesson_service_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateTestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lesson_service_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllTopicPlansByUIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lesson_service_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTopicPlanByIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lesson_service_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLessonByIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lesson_service_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllLessonPlansByTopicIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lesson_service_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllTestsByLessonIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lesson_service_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllQuestionsByTestIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lesson_service_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GradeTestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_lesson_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_lesson_service_proto_goTypes,
		DependencyIndexes: file_proto_lesson_service_proto_depIdxs,
		MessageInfos:      file_proto_lesson_service_proto_msgTypes,
	}.Build()
	File_proto_lesson_service_proto = out.File
	file_proto_lesson_service_proto_rawDesc = nil
	file_proto_lesson_service_proto_goTypes = nil
	file_proto_lesson_service_proto_depIdxs = nil
}
