FROM golang:1.22.1-alpine

WORKDIR /chat-service

COPY . .

RUN go mod download

RUN go get -u github.com/air-verse/air
RUN go install github.com/air-verse/air@latest

RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/chat-service

EXPOSE 8080

CMD [ "./main" ]