FROM golang:1.22.1-alpine

WORKDIR /user-subscription-service

COPY . .

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/user-subscription-service

EXPOSE 8080

CMD [ "./main" ]